api = "0.9"

[extension]
id = "paketo-community/ubi-java-extension"
name = "Paketo UBI Java Extension"
version = "{{.version}}"
description = "This extension installs the appropriate java runtime via dnf"

[metadata]
  include-files = ["LICENSE", "README.md", "bin/generate", "bin/detect", "bin/main", "extension.toml"]
  pre-package = "scripts/build.sh"

  [[metadata.configurations]]
    build = true
    default = "17"
    description = "the Java version"
    name = "BP_JVM_VERSION"


